@startuml

title Radium Engine build sequence\n
HelloRadium -> BaseApplication ++ : create()

    BaseApplication -> Engine : Engine::initialize()
    Engine -> EntityManager : create()
    note over Engine
    See diagram
    Engine initialization sequence
    end note
    Engine -> RenderObjectManager : create();

    BaseApplication -> GeometrySystem : instantiate( GeometrySystem )
    BaseApplication -> Engine : registerSystem( GeometrySystem )

    BaseApplication -> SimpleWindow : instantiate( SimpleWindow )
    SimpleWindow -> Viewer : create()

    BaseApplication -> SimpleWindow : show()
    SimpleWindow -> Viewer : show()
    Viewer -> SimpleWindow : initializedOpenGL()
    SimpleWindow -> ForwardRenderer : instantiate( ForwardRenderer )
    SimpleWindow -> Viewer : addRenderer( ForwardRenderer )
return


HelloRadium -> HelloRadium : build a mesh
HelloRadium -> HelloRadium : build the appearance

HelloRadium -> EntityManager : createEntity()
HelloRadium <- EntityManager : entity

HelloRadium -> TriangleMeshComponent ++ : createComponent("name", entity, mesh, appearance)
    TriangleMeshComponent -> RenderObject : build and parameterize render object
    note right TriangleMeshComponent
    See the diagram
    //Radium render object creation//
    end note
    TriangleMeshComponent -> RenderObjectManager : add render object
return  component
HelloRadium -> GeometrySystem : addComponent( entity, component );


HelloRadium -> SimpleWindow ++ : postLoadFile()
note over BaseApplication
This method should be renamed.
end note
    SimpleWindow -> Viewer : getRenderer()
    SimpleWindow <- Viewer : renderer
    SimpleWindow -> ForwardRenderer ++ : renderer.buildAllRenderTechniques()
        ForwardRenderer -> RenderObjectManager : getRenderObject()
        ForwardRenderer <- RenderObjectManager : ro
        ForwardRenderer -> RenderTechnique : build render passes
        ForwardRenderer -> RenderObject : parameterize render object
        ForwardRenderer -> RenderObjectManager : update (ro)
    return
return

HelloRadium -> BaseApplication ++ : exec
    BaseApplication -> Viewer : startRendering
    Viewer -> ForwardRenderer ++ : render()
    ForwardRenderer -> RenderObject : render
    note over TriangleMeshComponent
    See the diagram
    //Radium rendering sequence//
    end note
    return
    Viewer -> BaseApplication
return

HelloRadium -> BaseApplication ++ : destroy
    BaseApplication -> Engine : cleanup and destroy
return

@enduml
